version: 2.1

commands:
  install_dependencies:
    steps:
      - run: gem install bundler -v '2.2.14'
      - restore_cache:
          keys:
            - dls_template-{{ checksum "Gemfile" }}-{{ checksum "dls_template.gemspec" }}
      - run: bundle install --path ./vendor/bundle
      - save_cache:
          key: dls_template-{{ checksum "Gemfile" }}-{{ checksum "dls_template.gemspec" }}
          paths:
            - ./vendor/bundle
jobs:
  build:
    working_directory: ~/dls_template
    docker:
      - image: cimg/ruby:3.1.0-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - install_dependencies
      - persist_to_workspace:
          root: '~/dls_template'
          paths: '*'

  rubocop:
    working_directory: ~/dls_template
    docker:
      - image: cimg/ruby:3.1.0-browsers
        environment:
          RAILS_ENV: test
    steps:
      - attach_workspace:
          at: '~/dls_template'
      - install_dependencies
      - run:
          name: Run standardrb
          command: bundle exec standardrb

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - rubocop:
          requires:
            - build
